### ISSUE TITLE
Cant not download the VGG15.tfmodel

### ISSUE THREAD

**Issue by phongnhhn92** [ayush1997/Xvision#1]
Hello sir,
I am trying to extract features from train.py using VGG16. When i tried to download the file vgg16.tfmodel from https://s3.amazonaws.com/cadl/models/vgg16.tfmodel, seems like the link doesnt work for me. Would you mind providing alternative link for that file ?

**Comment by ayush1997** [comment]
Hi @phongnhhn92
The link should be working fine.Though I have uploaded it on drive also you can try it from here.
https://drive.google.com/open?id=0B-Xqlap3RsFuX0haOGtGUV9HMU0
