### ISSUE TITLE
input image size

### ISSUE THREAD

**Issue by Clintonrocks13** [ayush1997/Xvision#13]
Hello Mate , 

Greate job done !, can you please tell me how are you dealing with the input ?, as the xray jpg are single color Channel  images and VGG input tensor is i think of 3 channels . 
clinfernandes13@gmail.com
Thanks

**Comment by ayush1997** [comment]
Hi,
This [Line](https://github.com/ayush1997/Xvision/blob/master/DeepLearning/train.py#L114 ) reads it as a RGB image.Though all channels will be equal.
Sorry for a late reply.
