### ISSUE TITLE
train_model.py and test_model.py are reversed

### ISSUE THREAD

**Issue by TomaszRewak** [ayush1997/Xvision#15]
Files train_model.py and test_model.py are reversed. Right now (despite what readme says) one has to run test_model.py first and then train_model.py to validate the model. It seems that the content of these files is simply swapped.

**Comment by TomaszRewak** [comment]
Probably related: #9

**Comment by ayush1997** [comment]
Hi @TomaszRewak 
Thanks for this issue,I didn't notice but somehow it got accidentally changed around [this](https://github.com/ayush1997/Xvision/commit/288caafcf3b00f4f3895e86ec3c0d7756624eb7a) commit.

Thanks.
