### ISSUE TITLE
Code does not run as it is

### ISSUE THREAD

**Issue by icsimlai** [ayush1997/Xvision#17]
Is there a version dependency of "process.ipynb". When try to run the code as it is I get lots of errors in 
 Jupiter with Python 3, eg, following code does not run:
"c.items().sort(key=lambda x: x[0])"
has to be changed to ,
"sorted(c.items(), key=lambda x: x[0])"
No Print statements runs

**Comment by ayush1997** [comment]
It uses Python2.7

**Comment by icsimlai** [comment]
Do the python files in "DeepLearning" folder has same dependency on Python2.7? Do you have a plan to update to Python 3? With almost zero comments in the code it's difficult for someone else to do the same.

**Comment by icsimlai** [comment]
When trying to run I get errors as shown below:
python scraper.py "."
extract
Traceback (most recent call last):
  File "scraper.py", line 72, in <module>
    main()
  File "scraper.py", line 68, in main
    extract(link)
  File "scraper.py", line 47, in extract
    urllib.urlretrieve(domain+img, path+str(img_no)+".png")
AttributeError: module 'urllib' has no attribute 'urlretrieve'

**Comment by ayush1997** [comment]
That has to do with the python version.
I do not have any plans to update it to 3 as of now.

**Comment by icsimlai** [comment]
Hi,
Is the following code correct, specially "elif" blocks?
train_images_dict = {}
test_images_dict={}
for  i in index_list:
#     print i
    if i== "normal":
        train_images_dict["normal"]=index_list[i][400:500]
        test_images_dict["normal"] = index_list[i][500:550]
#...
    elif i=="nodule" :
        train_images_dict[i]=index_list[i][:54]
        test_images_dict[i] = index_list[i][49:]
    elif i=="calcinosisnodule":
        train_images_dict["nodule"]+=index_list[i][:23]
        test_images_dict["nodule"] += index_list[i][23:]
Regards,

**Comment by icsimlai** [comment]
Hi,
Is the following code correct, specially "elif" blocks?

train_images_dict = {}
test_images_dict={}
count = 1
for  i in index_list:

    if i== "normal":
        train_images_dict["normal"]=index_list[i][100:200]
        test_images_dict["normal"] = index_list[i][201:250]
 
    elif i=="nodule" :
        train_images_dict[i]=index_list[i][:54]
        test_images_dict[i] = index_list[i][49:]

    elif i=="calcinosisnodule":
        train_images_dict['calcinosisnodule'] = index_list[i][:23]
        test_images_dict["calcinosisnodule"] = index_list[i][23:]
