### ISSUE TITLE
Problem with process.ipynb

### ISSUE THREAD

**Issue by gaurav-b98** [ayush1997/Xvision#18]
Hey Ayush,
    While using your code I ran into a problem and saw that your training image list in your jupyter notebook was looping for only 177 images and not the whole dataset and I couldn't find any solution regarding it. If you could help me with this it would be a very big help.

Thank you.

**Comment by ayush1997** [comment]
Hey,
Since I am only looking at "nodular" images that's why only those images and normal images(to balance it) are extracted.
I would suggest you to look at the [dataset](https://nihcc.app.box.com/v/ChestXray-NIHCC/folder/37178474737) released by NIH, it has quite a good number of images.

**Comment by gaurav-b98** [comment]
Ok. Thank you. :)
