### ISSUE TITLE
train.py has issue with tensorflow 0.12

### ISSUE THREAD

**Issue by TestoutSoftware** [ayush1997/Xvision#6]
Hi Ayush, 
I got an error when parse VGGNet-16 with tensorflow V 0.12. Any idea about tensorflow version that you use?

Thanks
TSW

**Comment by TestoutSoftware** [comment]
same issue as umar-sharif

**Comment by ayush1997** [comment]
Hi
So I am using python2.7 and Tensorflow0.11. There are changes in v0.12 which might lead to some issues.
